import type { DataShape } from "./types";
import { countryName } from "./countries";

/** Stable placeholder helpers (picsum supports a deterministic seed). */
const img = (seed: string, w: number, h: number) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

const SAMPLE_VIDEO =
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";

export const SEED: DataShape = {
  settings: {
    siteName: "LUMEN",
    tagline: "Cinematic photography & film for modern brands.",
    logo: img("lumen-logo", 320, 320),
    reelVideoUrl: SAMPLE_VIDEO,
    reelPoster: img("studio-reel", 720, 1280),
    briefHeading: "A studio built on light & motion.",
    brief:
      "We craft bold, three-dimensional imagery for automotive, fashion and architecture brands — and cinematic films that move them. Every frame is shot, graded and finished in-house.",
    brandsSpeed: 7,
    email: "hello@lumen.studio",
    instagram: "@lumen.studio",
    linkedin: "https://linkedin.com/company/lumen-studio",
    facebook: "https://facebook.com/lumen.studio",
    whatsapp: "+1 555 010 2030",
    whatsappMessage: "Hi LUMEN! I'd love to book a shoot.",
    calendarUrl: "https://calendar.app.google/your-booking-link",
  },
  stats: [
    {
      id: "stat-countries",
      label: "Countries we worked with",
      value: 14,
      suffix: "+",
      icon: "globe",
      createdAt: "2026-02-01T09:00:00.000Z",
    },
    {
      id: "stat-clients",
      label: "Happy clients",
      value: 180,
      suffix: "+",
      icon: "users",
      createdAt: "2026-02-01T09:01:00.000Z",
    },
    {
      id: "stat-projects",
      label: "Projects delivered",
      value: 320,
      suffix: "+",
      icon: "camera",
      createdAt: "2026-02-01T09:02:00.000Z",
    },
    {
      id: "stat-years",
      label: "Years in the craft",
      value: 9,
      suffix: "",
      icon: "award",
      createdAt: "2026-02-01T09:03:00.000Z",
    },
  ],
  countries: [
    "us", "gb", "fr", "de", "it", "es", "jp", "ae",
    "sa", "eg", "au", "ca", "br", "in",
  ].map((code, i) => ({
    id: `country-${code}`,
    code,
    name: countryName(code),
    createdAt: `2026-02-01T10:${String(i).padStart(2, "0")}:00.000Z`,
  })),
  categories: [
    {
      id: "cat-automotive",
      medium: "photography",
      name: "Automotive",
      slug: "automotive",
      description: "Hypercars, classics and showroom builds shot in studio and on location.",
      coverImage: img("auto-cover", 320, 320),
      accent: "#d946ef",
      createdAt: "2026-02-01T09:00:00.000Z",
    },
    {
      id: "cat-fashion",
      medium: "photography",
      name: "Fashion",
      slug: "fashion",
      description: "Editorial, runway and lookbook photography for modern labels.",
      coverImage: img("fashion-cover", 320, 320),
      accent: "#22d3ee",
      createdAt: "2026-02-04T09:00:00.000Z",
    },
    {
      id: "cat-architecture",
      medium: "photography",
      name: "Architecture",
      slug: "architecture",
      description: "Interiors, exteriors and spatial storytelling for studios and developers.",
      coverImage: img("arch-cover", 320, 320),
      accent: "#a3e635",
      createdAt: "2026-02-09T09:00:00.000Z",
    },
    {
      id: "cat-commercials",
      medium: "videography",
      name: "Commercials",
      slug: "commercials",
      description: "Brand films, product launches and broadcast spots.",
      coverImage: img("commercials-cover", 320, 320),
      accent: "#fbbf24",
      createdAt: "2026-02-18T09:00:00.000Z",
    },
  ],
  brands: [
    {
      id: "brand-velocity",
      categoryIds: ["cat-automotive"],
      name: "Velocity Motors",
      logo: img("velocity-logo", 240, 240),
      description: "Performance EV manufacturer — launch campaign 2026.",
      website: "https://example.com",
      featured: true,
      createdAt: "2026-02-02T09:00:00.000Z",
    },
    {
      id: "brand-aurora",
      categoryIds: ["cat-automotive"],
      name: "Aurora Classics",
      logo: img("aurora-logo", 240, 240),
      description: "Restored vintage automobiles and concours builds.",
      featured: false,
      createdAt: "2026-02-03T09:00:00.000Z",
    },
    {
      id: "brand-noir",
      categoryIds: ["cat-fashion"],
      name: "Maison Noir",
      logo: img("noir-logo", 240, 240),
      description: "Avant-garde Paris label — FW26 lookbook.",
      website: "https://example.com",
      featured: true,
      createdAt: "2026-02-05T09:00:00.000Z",
    },
    {
      id: "brand-form",
      categoryIds: ["cat-architecture"],
      name: "Form Studio",
      logo: img("form-logo", 240, 240),
      description: "Minimalist residential architecture practice.",
      featured: false,
      createdAt: "2026-02-10T09:00:00.000Z",
    },
    {
      id: "brand-apex",
      categoryIds: ["cat-commercials"],
      name: "Apex Films",
      logo: img("apex-logo", 240, 240),
      description: "Cinematic commercial production house.",
      website: "https://example.com",
      featured: true,
      createdAt: "2026-02-19T09:00:00.000Z",
    },
  ],
  photos: [
    {
      id: "photo-2",
      brandId: "brand-velocity",
      section: "gallery",
      title: "Detail — wheel & brake",
      orientation: "portrait",
      url: img("velocity-2", 800, 1200),
      createdAt: "2026-02-12T10:00:00.000Z",
    },
    {
      id: "photo-3",
      brandId: "brand-velocity",
      section: "gallery",
      title: "Cockpit interior",
      orientation: "landscape",
      url: img("velocity-3", 1200, 800),
      createdAt: "2026-02-13T09:00:00.000Z",
    },
    {
      id: "photo-1",
      brandId: "brand-velocity",
      section: "bts",
      title: "Color grade — before / after",
      orientation: "landscape",
      url: img("velocity-1", 1200, 800),
      beforeUrl: img("velocity-1-raw", 1200, 800),
      afterUrl: img("velocity-1", 1200, 800),
      createdAt: "2026-02-12T09:00:00.000Z",
    },
    {
      id: "photo-5",
      brandId: "brand-noir",
      section: "gallery",
      title: "Look 02 — detail",
      orientation: "portrait",
      url: img("noir-2", 800, 1200),
      createdAt: "2026-02-14T10:00:00.000Z",
    },
    {
      id: "photo-4",
      brandId: "brand-noir",
      section: "bts",
      title: "Retouch — before / after",
      orientation: "portrait",
      url: img("noir-1", 800, 1200),
      beforeUrl: img("noir-1-raw", 800, 1200),
      afterUrl: img("noir-1", 800, 1200),
      createdAt: "2026-02-14T09:00:00.000Z",
    },
    // --- Videography (Apex Films): gallery + BTS items are videos ---
    {
      id: "vid-1",
      brandId: "brand-apex",
      section: "gallery",
      title: "Hero spot — 30s cut",
      orientation: "landscape",
      url: img("apex-1", 1280, 720),
      videoUrl: SAMPLE_VIDEO,
      durationSec: 30,
      createdAt: "2026-02-20T09:00:00.000Z",
    },
    {
      id: "vid-2",
      brandId: "brand-apex",
      section: "gallery",
      title: "Vertical teaser",
      orientation: "portrait",
      url: img("apex-2", 720, 1280),
      videoUrl: SAMPLE_VIDEO,
      durationSec: 15,
      createdAt: "2026-02-20T10:00:00.000Z",
    },
    {
      id: "vid-3",
      brandId: "brand-apex",
      section: "bts",
      title: "On-set rig walkthrough",
      orientation: "landscape",
      url: img("apex-bts-1", 1280, 720),
      videoUrl: SAMPLE_VIDEO,
      durationSec: 64,
      createdAt: "2026-02-21T09:00:00.000Z",
    },
  ],
  reels: [
    {
      id: "reel-1",
      brandId: "brand-velocity",
      title: "BTS — studio lighting setup",
      videoUrl: SAMPLE_VIDEO,
      thumbnail: img("velocity-bts-1", 600, 1066),
      durationSec: 38,
      createdAt: "2026-02-15T09:00:00.000Z",
    },
    {
      id: "reel-2",
      brandId: "brand-noir",
      title: "BTS — runway walkthrough",
      videoUrl: SAMPLE_VIDEO,
      thumbnail: img("noir-bts-1", 600, 1066),
      durationSec: 52,
      createdAt: "2026-02-16T09:00:00.000Z",
    },
    {
      id: "reel-3",
      brandId: "brand-apex",
      title: "BTS — gimbal run",
      videoUrl: SAMPLE_VIDEO,
      thumbnail: img("apex-bts-reel", 600, 1066),
      durationSec: 41,
      createdAt: "2026-02-22T09:00:00.000Z",
    },
  ],
};
